import Files from "./FilesPath"
  const pdfFiles=[
    {
       Id:1,
       Name:"Week1",
       Author:"author1",
       Src:Files.file1
     },
     {
       Id:2,
       Name:"week2",
       Author:"author2",
       Src:Files.file2
     },
     {
       Id:3,
       Name:"week3",
       Author:"author3",
       Src:Files.file3
     },
     {
       Id:4,
       Name:"week3e",
       Author:"author1",
       Src:Files.file3e
     },
     {
       Id:5,
       Name:"week4",
       Author:"author2",
       Src:Files.file4
     },
     {
       Id:6,
       Name:"week4e",
       Author:"author3",
       Src:Files.file4e
     },
     {
       Id:7,
       Name:"week5",
       Author:"author1",
       Src:Files.file5
     },
     {
       Id:8,
       Name:"week5e",
       Author:"author2",
       Src:Files.file5e
     },
     {
       Id:9,
       Name:"week6",
       Author:"author3",
       Src:Files.file6
     },
     {
       Id:10,
       Name:"week6e",
       Author:"author1",
       Src:Files.file6e
     },
     {
       Id:11,
       Name:"week7",
       Author:"author2",
       Src:Files.file7
     },
     {
       Id:12,
       Name:"week9",
       Author:"author3",
       Src:Files.file9
     },
     {
       Id:13,
       Name:"week9e",
       Author:"week9e",
       Src:Files.file9e
     },
     {
       Id:14,
       Name:"week10",
       Author:"author2",
       Src:Files.file10
     },
     {
       Id:15,
       Name:"week10e",
       Author:"author3",
       Src:Files.file10e
     },
     {
       Id:16,
       Name:"week11",
       Author:"author1",
       Src:Files.file11
     },
     {
       Id:17,
       Name:"week11e",
       Author:"author2",
       Src:Files.file11e
     },
     {
       Id:18,
       Name:"week12",
       Author:"author3",
       Src:Files.file12
     },
     {
       Id:19,
       Name:"week12e",
       Author:"author1",
       Src:Files.file12e
     },
     {
       Id:20,
       Name:"week13",
       Author:"author2",
       Src:Files.file13
     },
    
   ];

   export default pdfFiles;